// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyiwriuidahkgadjrzeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5aXdyaXVpZGFoa2dhZGpyemVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3ODk1MTksImV4cCI6MjA1ODM2NTUxOX0.ILKXt9qrR3YoF9DxE4MT3dS-UUYOrdZ6tEc5hEJrUp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);