// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izqkrualnethkxfmpqql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6cWtydWFsbmV0aGt4Zm1wcXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDYwNDQsImV4cCI6MjA1ODQ4MjA0NH0._DG8MhCOaPjDM_VwofQDfZmkAERUJ75lV18LHsYewvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);